### PR TITLE
Updated clientscheme to use #base method

### PR DESCRIPTION
**Pull request by scrufulufugus**
Its much nicer

### CODE REVIEW

**Comment by Sevin7** [comment]
What's so much nicer about it? Looks like it just separates things.

**Comment by scrufulufugus** [comment]
Much easier to read and edit then a 8000 line file and it can prevent some crash issues after updates.

**Comment by scrufulufugus** [comment]
If you don't want it, I'll close the request, I just did the work and thought you might be able to use it

**Comment by Sevin7** [comment]
I appreciate it. I'm still deciding. I will close it when I decide to merge
or not to merge.

**Comment by Sevin7** [comment]
Decided not to use it. If I end up wanting to modify a default feature, I don't really want to be copying back and forth from separate files. It won't make updates any easier.

**Pull request closed without merging**
