### PR TITLE
make DashboardDimmer invisible

### PR DESCRIPTION
**Pull request by mastercoms**
I'm not sure if you wanted the dimmer to be hidden, or to take up the whole screen. This PR makes it hidden.

### CODE REVIEW

**Comment by Sevin7** [comment]
No way, I thought everyone agreed it was hardcoded.

**Comment by Sevin7** [comment]
Did you test this? It doesn't work for me. I think I remember trying this when the dimmer was added.

**Comment by mastercoms** [comment]
Yeah, it works for me

**Comment by mastercoms** [comment]
maybe I didn't catch a change but that should be it

**Comment by mastercoms** [comment]
Ah, it's because while I was testing, it reloaded the HUD and replaced the element.

**Pull request closed without merging**
