### PR TITLE
Added background for Gun Mettle update

### PR DESCRIPTION
**Pull request by 1112e**

### CODE REVIEW

**Comment by Sevin7** [comment]
Thanks for doing this, but 7HUD has a custom background and I'd like to
keep it that way.

**Comment by 1112e** [comment]
Fair enough. Will you be fixing the hud for the update? scoreboard and a few other things seem to be broken

**Comment by Sevin7** [comment]
I will do my utmost. I have to wait for the patches page on the wiki to be
updated so I know what to change, however, so I may not be able to start
until tomorrow.

**Comment by 1112e** [comment]
Sounds good! I appreciate your work!

**Pull request closed without merging**
